Discussion 2

In [1]:
import numpy as np
from math import *
import matplotlib.pyplot as plt

## Scale: first we will create a scale matrix

Suppose I want to scale the x-axis by 1 and the y-axis by 2

In [2]:
sx=1
sy=2

I will create a scale matrix

In [3]:
s = np.array([[sx, 0, 0],
              [0, sy, 0],
              [0, 0, 1]])
print('s: ', s)

s:  [[1 0 0]
 [0 2 0]
 [0 0 1]]


## Scaling Example...Pick some points

In [4]:
pts = np.array([1, 1, 0]) # as (x, y, z)
s_times_pts = np.dot(s, pts)
print(s_times_pts)

[1 2 0]


### Pick box points

In [5]:
# pick more points:
left_bottom = [1,1,0, 0]
left_top = [1,2,0, 0]
right_bottom = [2,1,0, 0]
right_top = [2,2,0, 0]

pts = np.array([left_bottom, left_top, right_bottom, right_top])
# s.times_pts = np.dot(s, pts)
print('pts: ', pts.T)
s = np.array([[sx, 0, 0, 0], 
     [0, sy, 0, 0],
     [0, 0, 1, 0],
     [0, 0, 0, 1]])
res = np.dot(s, pts.T)
print('s.times pts', res)
print('You can observe that it simply scales the Y component')


pts:  [[1 1 2 2]
 [1 2 1 2]
 [0 0 0 0]
 [0 0 0 0]]
s.times pts [[1 1 2 2]
 [2 4 2 4]
 [0 0 0 0]
 [0 0 0 0]]
You can observe that it simply scales the Y component


In [6]:
print('new_LB: ', res[:,0][0:2])
print('new_LT: ', res[:,1][0:2])
print('new_RB: ', res[:,2][0:2])
print('new_RT: ', res[:,3][0:2])


new_LB:  [1 2]
new_LT:  [1 4]
new_RB:  [2 2]
new_RT:  [2 4]


## Rotation

Now I will create a rotation matrix
$$\
  M=
  \left[ {\begin{array}{ccc}
   cos(\theta) & -sin(\theta) & 0\\
   sin(\theta) & cos(\theta) & 0\\
   0 & 0 & 1\\
  \end{array} } \right]
]
$$

Note: This will rotate $\theta$ counter clockwise in the x,y plane

In [7]:
theta = pi/4
get_rotation = lambda theta: np.array([[cos(theta), -1*sin(theta), 0],
                                       [sin(theta), cos(theta),  0],
                                       [0,                   0,  1]])
r = get_rotation(theta)
print('R: ', r)

R:  [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


$$\
  R=
  \left[ {\begin{array}{ccc}
   \frac{\sqrt(2)}{2} & -\frac{\sqrt(2)}{2} & 0\\
   \frac{\sqrt(2)}{2} & \frac{\sqrt(2)}{2} & 0\\
   0 & 0 & 1\\
  \end{array} } \right]
]
$$

Determinant of R

In [ ]:
Rx * Ry * Rz (pts)

In [8]:
print(np.linalg.det(r))

1.0


Det is 1 because volume is preserved!

is $s*r$ different from $r*s$?
- Yes

In [9]:
s = np.array([[sx,0,0],[0, sy, 1],[0, 0, 1]])

In [10]:
print(s)

[[1 0 0]
 [0 2 1]
 [0 0 1]]


In [13]:
r

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [11]:
r_times_s = np.dot(r,s)
print('rotate_scale')
print(r_times_s)

rotate_scale
[[ 0.70710678 -1.41421356 -0.70710678]
 [ 0.70710678  1.41421356  0.70710678]
 [ 0.          0.          1.        ]]


In [12]:
s_times_r = np.dot(s, r)
print('scale_rotate')
print(s_times_r)

scale_rotate
[[ 0.70710678 -0.70710678  0.        ]
 [ 1.41421356  1.41421356  1.        ]
 [ 0.          0.          1.        ]]


From here we can see that these are different transformation matrices!...Hence the property of commutativity does not hold!

### Sidenote: If we use different rotation matrix (for reflections)

Lets say we use this rotation matrix instead...
  $$\hat{R}=
  \left[ {\begin{array}{ccc}
   cos(\theta) & sin(\theta) & 0\\
   sin(\theta) & -cos(\theta) & 0\\
   0 & 0 & 1\\
  \end{array} } \right]
$$

In [14]:
r_reflection = np.array([[cos(theta), sin(theta), 0],
             [sin(theta), -1*cos(theta),  0],
             [0,  0, 1]])

In [15]:
print(np.linalg.det(r_reflection))

-1.0


The determinant is -1 because we reflect about the XY axis